# .github/workflows/esp-matter-ci.yml
name: Build esp-matter icd_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clone ESP-IDF
      run: |
        git clone --depth=1 -b v5.4.2 https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
      shell: bash

    - name: Set up build environment
      run: |
        export IDF_PATH=$GITHUB_WORKSPACE/esp-idf
        . $IDF_PATH/export.sh
      shell: bash

    - name: Build icd_app project
      run: |
        export IDF_PATH=$GITHUB_WORKSPACE/esp-idf
        . $IDF_PATH/export.sh
        idf.py set-target esp32c6
        idf.py build
      shell: bash

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: icd_app_build
        path: build/
