# .github/workflows/ci.yml
name: Build ICD_APP (esp-matter via idf-component-manager)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clone ESP-IDF
      run: |
        git clone --depth=1 -b v5.4.2 https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
      shell: bash

    - name: Set IDF_PATH env
      run: |
        echo "IDF_PATH=$GITHUB_WORKSPACE/esp-idf" >> $GITHUB_ENV
      shell: bash

    - name: Build project with idf-component-manager
      run: |
        . $IDF_PATH/export.sh
        idf.py set-target esp32c6
        idf.py reconfigure    # dependencies download
        idf.py build
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: icd_app_build
        path: build/
